name: workout_tracking
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter_timezone: ^1.0.6
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  flutter_calendar_carousel: ^2.4.2
  simple_circular_progress_bar: ^1.0.2
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.0.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.0.0
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0 
  freezed: ^2.0.0 
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/images/
    - assets/json/exercises.json
    - assets/json/meals.json

